# GitHub Funding Configuration
# This file enables funding links on the repository

# GitHub Sponsors
github: khokanuzzman

# Open Collective
open_collective: react-native-flipper-inspector

# Ko-fi
ko_fi: khokanuzzman

# Custom funding links (Portfolio, etc.)
custom:
  - https://khokanuzzman.github.io/
